site_name: my-project

site_author: Fnanshan

site_favicon: favicon.ico

#nav:
#- Home: ['index.md', 'helloworld']
#- mkdocs: ['use_mkdocs.md']

nav:
    - Home: index.md
    - python_web: python_web_framework.md
    - About: about.md

theme: readthedocs
# theme: mkdocs

repo_url: https://github.com/Fnanshan/repository/

repo_name: Github



google_analytics: ['UA-36723568-3', 'mkdocs.org']