# Generated by Django 2.2.5 on 2019-09-26 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bbs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bbs',
            name='bbshot',
        ),
    ]
