# Generated by Django 2.2.5 on 2019-09-26 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbs', '0002_remove_bbs_bbshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='bbs',
            name='bbshot',
            field=models.BinaryField(default=False, verbose_name='是否为精华帖'),
        ),
    ]
