# Generated by Django 2.2.5 on 2019-10-10 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_person'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='person',
            managers=[
            ],
        ),
    ]
