# Generated by Django 2.2.5 on 2019-10-05 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_opinionpoll_response'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='opinionpoll',
            managers=[
            ],
        ),
    ]
