# Generated by Django 2.2.5 on 2019-10-10 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20191005_0852'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='image',
            field=models.ImageField(default=0, height_field=200, upload_to='', width_field=300),
            preserve_default=False,
        ),
    ]
