# Generated by Django 2.2.5 on 2019-10-10 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_choice_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='response',
            name='poll',
        ),
        migrations.RemoveField(
            model_name='choice',
            name='image',
        ),
        migrations.DeleteModel(
            name='OpinionPoll',
        ),
        migrations.DeleteModel(
            name='Response',
        ),
    ]
